Formatting changes
vtantia/fairscale pull request #1
Opened 2021-02-09 22:13 UTC by vtantia

Intermediate work while creating documentation

2021-02-10 14:28 UTC, mikerabbat requested changes
Please see the inline comments for some questions.

Does the slowmo implementation allow for doing no sharding (i.e., keeping and updating a full copy of the slowmo state at every worker, as was done in the original SlowMo paper?

2021-02-10 14:28 UTC, mikerabbat commented on fairscale/nn/data_parallel/gossip/distributed.py
> +        slowmo_frequency (int): This specifies how often slow momentum is to be performed.
I would remove the line saying "This does not need to be tuned generally" because I think it really does depend on the application. (For other applications, we've been using much smaller values, around 8-12.)

Also, after "how often" you could specify the units to make it more precise: "This specifies how often (iterations) slow momentum..."

2021-02-10 14:28 UTC, mikerabbat commented on fairscale/nn/data_parallel/gossip/distributed.py
> +                  https://arxiv.org/abs/1910.00643 for more details). This does not need to
Rather than "This does not need to be tuned generally." I'd suggest changing to the stronger wording "We do not recommend changing this."

2021-02-10 14:28 UTC, mikerabbat commented on fairscale/nn/data_parallel/gossip/distributed.py
> +        nprocs_per_node (int): Number of GPUs per node. This needs to be specified for
In the code this has a default value, but it seems like it may be better to remove the default value and force the user to specify it. What do you think? (No default is mentioned in the documentation.)

2021-02-10 14:28 UTC, mikerabbat commented on fairscale/nn/data_parallel/gossip/distributed.py
> +        slowmo_num_shards (int): The number of shards between which slow momentum parameters
I worry that the description here may not be sufficient for a new user to understand this functionality.

Also, I looked through the code quickly, but I think I'm missing something. Is there a default setting where we don't do any sharding (so each process keeps a full copy of the slowmo state? I would expect that to be the default (how the algorithm was originally described in the paper), and we only shard if the user actually species to do so. (Using sharding reduces the memory footprint but increases communication overhead, right?)

Right now the default to use 32 shards seems pretty arbitrary.

2021-02-10 14:28 UTC, mikerabbat commented on fairscale/nn/data_parallel/gossip/distributed.py
> +        graph: Optional[GraphManager] = None,
I guess the documentation for these parameters still needs to be added?

2021-02-10 14:28 UTC, mikerabbat commented on fairscale/nn/data_parallel/gossip/distributed.py
> +        Only for advanced users
Could add a note here that if these are not specified, the default behavior is to get them from the torch.distributed module

2021-02-10 14:28 UTC, mikerabbat commented on fairscale/nn/data_parallel/gossip/distributed.py
> +        >>> net = fairscale.data_parallel.GossipDataParallel(model, pg, nprocs_per_node)
What is `pg` in this example?

2021-02-10 14:28 UTC, mikerabbat commented on fairscale/nn/data_parallel/gossip/distributed.py
> +        If fp16 training is being done, the last line changes to
Formatting looks weird, a line of text (comment?) in the middle of lines of code

2021-02-10 14:28 UTC, mikerabbat commented on fairscale/nn/data_parallel/gossip/utils/helpers.py
> +# TODO: deprecate this function
Is this function still used in the current implementation? If not, may as well clean it up before sending the PR

2021-02-10 14:34 UTC, vtantia commented on fairscale/nn/data_parallel/gossip/distributed.py
> +    To use ``DistributedDataParallel`` on a host with N GPUs, you should spawn
Should we point them to the DDP documentation in that case?

2021-02-10 14:35 UTC, vtantia commented on fairscale/nn/data_parallel/gossip/utils/helpers.py
> +# TODO: deprecate this function
This is being used in sgp_gossip_target. I've made it a future TODO to get rid of it

2021-02-10 14:38 UTC, vtantia commented on fairscale/nn/data_parallel/gossip/distributed.py
> +        slowmo_frequency (int): This specifies how often slow momentum is to be performed.
In those cases, how did you choose 8-12 (was it through tuning)? I had added this based on my experience with tuning it on Imagenet for vision, and the WMT 16 En-De dataset for translation, but can definitely change this

2021-02-10 14:39 UTC, mikerabbat commented on fairscale/nn/data_parallel/gossip/distributed.py
> +    To use ``DistributedDataParallel`` on a host with N GPUs, you should spawn
It just seems strange to me because this is the documentation for GossipDataParallel (or SlowmoDataParallel), so why are we talking about how to use `DistributedDataParallel` here?

2021-02-10 14:41 UTC, mikerabbat commented on fairscale/nn/data_parallel/gossip/distributed.py
> +        slowmo_frequency (int): This specifies how often slow momentum is to be performed.
Yes, based on experimenting/tuning. Basically, increasing frequency has diminishing returns in terms of how much time is saved, and increasing it can also degrade performance. So using smaller values sometimes will give better accuracy without really changing the runtime much.

2021-02-10 14:43 UTC, vtantia commented on fairscale/nn/data_parallel/gossip/distributed.py
> +    To use ``DistributedDataParallel`` on a host with N GPUs, you should spawn
Ahh I see the point you mean. I didn't get the meaning of copy-pasta haha

2021-02-10 15:02 UTC, odelalleau commented on fairscale/nn/data_parallel/gossip/distributed.py
> +        self.slowmo = False if slowmo_lr == 1 and slowmo_momentum == 0 else True
```suggestion
        self.slowmo = slowmo_lr != 1 or slowmo_momentum != 0
```

2021-02-10 17:47 UTC, vtantia commented on fairscale/nn/data_parallel/gossip/distributed.py
> +        slowmo_num_shards (int): The number of shards between which slow momentum parameters
I shall explain this more in the comment for slowmo_memory_efficient, a new parameter I have added to handle your second concern. That is in another branch and I send it to you for review.

The default was chosen by doing some preliminary tuning. With this value, the amortized time taken by SlowMo is quite negligible (on the order of a few milliseconds) so we went ahead with this value. We can revisit this number in the future if the need arises

2021-02-10 18:27 UTC, mikerabbat approved these changes
Looks good!

2021-02-10 18:27 UTC, mikerabbat commented on fairscale/nn/data_parallel/gossip/distributed.py
> +        slowmo_num_shards (int): The number of shards between which slow momentum parameters
I think it's fine to leave it as a default and let a user adjust it as they see fit.

2021-02-19 14:38 UTC, vtantia commented
Merged into slowmo

2021-02-19 14:38 UTC, closed without merging